### ISSUE TITLE
希望添加是否自动format的设置开关，同时提供一个快捷菜单或者快捷键

### ISSUE THREAD

**Issue by zhu-xiaoming** [huacnlee/vscode-auto-correct#1]
很多项目是多人维护的，现在默认自动format，导致改动commit时发现了一堆改动

是否考虑添加一个自动format的设置开关，然后添加个右键菜单或者快捷键？

**Comment by zhu-xiaoming** [comment]
额，发现由于自动格式化了字符串，导致前端显示的文案多了一些空格，不符合视觉稿了 😂

看来还是需要一个开关

**Comment by huacnlee** [comment]
某些文件可以单独设置的，在文件头增加注释

```
// autocorrect: false
```

可以禁用掉单个文件

另外 VS Code 插件里面，可以设置 formatOnSave 的开关，然后手工执行命令来个格式化。

**Comment by huacnlee** [comment]
升级插件，现在可以了。
